### ISSUE TITLE
Getting NoLayoutException error

### ISSUE THREAD

**Issue by edpark1** [plotly/dash-salesforce-crm#5]
Trying to run the site.  I am running 3.6.6 with all requirements satisfied.

flask run
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 145-409-595
127.0.0.1 - - [12/Apr/2019 12:55:47] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/edp/.pyenv/versions/3.6.6/envs/my-virtual-env-3.6.6/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/edp/.pyenv/versions/3.6.6/envs/my-virtual-env-3.6.6/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/edp/.pyenv/versions/3.6.6/envs/my-virtual-env-3.6.6/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/edp/.pyenv/versions/3.6.6/envs/my-virtual-env-3.6.6/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/edp/.pyenv/versions/3.6.6/envs/my-virtual-env-3.6.6/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/edp/.pyenv/versions/3.6.6/envs/my-virtual-env-3.6.6/lib/python3.6/site-packages/flask/app.py", line 1808, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/Users/edp/.pyenv/versions/3.6.6/envs/my-virtual-env-3.6.6/lib/python3.6/site-packages/flask/app.py", line 1855, in try_trigger_before_first_request_functions
    func()
  File "/Users/edp/.pyenv/versions/3.6.6/envs/my-virtual-env-3.6.6/lib/python3.6/site-packages/dash/dash.py", line 994, in _setup_server
    self._validate_layout()
  File "/Users/edp/.pyenv/versions/3.6.6/envs/my-virtual-env-3.6.6/lib/python3.6/site-packages/dash/dash.py", line 971, in _validate_layout
    ''
**dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called. Make sure to set the `layout` attribute of your application before running the server.**
127.0.0.1 - - [12/Apr/2019 12:55:47] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [12/Apr/2019 12:55:47] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [12/Apr/2019 12:55:47] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [12/Apr/2019 12:55:48] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [12/Apr/2019 12:55:48] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [12/Apr/2019 12:55:48] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

**Comment by cldougl** [comment]
@edpark1 can you verify you've installed the requirements in the requirements.txt file,  you can try running `python index.py`. Please note that you must create/use your own salesforce developer account.

**Comment by alexdatadesign** [comment]
Got the same results, 
```
dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called. Make sure to set the `layout` attribute of your application before running the server.
```

**Comment by VictorBezak** [comment]
@alexdatadesign Are you attempting to run an exact copy of this repository or have you made modifications to its file structure or code?
